[project]
name = "gans"
version = "0.1.0"
description = "Learning about Generative Image Models"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "mlx>=0.29.4",
    "numpy>=2.3.4",
    "plotly>=6.4.0",
    "seaborn>=0.13.2",
]
